name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://jenkins.mrjeffapp.net"
        user: "jenkins"
        token: ${{ secrets.TOKEN }}
        job: "k8s-module-jeff-pull-request-tester"
