name: Test Job

on:
  push
jobs:
  testJob:
    runs-on: ubuntu-18.04
    steps:
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1
      - name: Install aws-cli
        uses: chrislennon/action-aws-cli@v1.1
      # All commands after this point have access to the AWS CLI
      - name: Add SG rule
        run: aws ec2 authorize-security-group-ingress --group-name github-actions-to-jenkins --protocol tcp --port 443 --cidr ${{ steps.ip.outputs.ipv4 }}/32 --region eu-west-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: actions/checkout@v1
      - name: Trigger Jenkins job
        run: |
          pip3 install requests
          python3 $GITHUB_WORKSPACE/.github/workflows/jenkins-executer.py victormartinez:${{ secrets.TOKEN }} https://jenkins.mrjeffapp.net k8s-module-jeff-pull-request-tester
      - name: Delete SG rule
        if: ${{ always() }}
        run: aws ec2 revoke-security-group-ingress --group-name github-actions-to-jenkins --protocol tcp --port 443 --cidr ${{ steps.ip.outputs.ipv4 }}/32 --region eu-west-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

